---
- name: Ensure dependencies are installed.
  package:
    name:
      - curl
      - initscripts
      - "{{ 'libselinux-python' if ansible_python['version']['major'] < 3 else 'python3-libselinux' }}"
    state: present

- name: AdoptOpenJDK yum repository
  yum_repository:
    name: AdoptOpenJDK
    description: AdoptOpenJDK
    baseurl: http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos/$releasever/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
- name: Endpoint yum repository
  yum_repository:
    name: endpoint
    description: End Point repository
    baseurl: https://packages.endpoint.com/rhel/$releasever/os/$basearch/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.endpoint.com/endpoint-rpmsign-7.pub
# - name: remove any installed git
#   yum:
#     name: git
#     state: absent
- name: Install fontconfig, AdoptOpenJDK and git
  yum:
    name:
      - fontconfig
      - adoptopenjdk-11-hotspot
      - git
      - wget
    state: latest